#include<iostream>
using namespace std;

int main () {
    cout<<endl<<endl;
    cout<<"Numerical values of Alphabets A to Z are as follows: "<<endl;
    char ch1 = 'A';
    int a = (int)ch1-64;
    cout<<"A = "<<a<<endl;
    char ch2 = 'B';
    int b = (int)ch2-64;  
    cout<<"B = "<<b<<endl;
    char ch3 = 'C';
    int c = (int)ch3-64;
    cout<<"C = "<<c<<endl;
    char ch4 = 'D';
    int d = (int)ch4-64;
    cout<<"D = "<<d<<endl;
    char ch5 = 'E';
    int e = (int)ch5-64;
    cout<<"E = "<<e<<endl;
    char ch6 = 'F';
    int f = (int)ch6-64;
    cout<<"F = "<<f<<endl;
    char ch7 = 'G';
    int g = (int)ch7-64;
    cout<<"G = "<<g<<endl;
    char ch8 = 'H';
    int h = (int)ch8-64;
    cout<<"H = "<<h<<endl;
    char ch9 = 'I';
    int i = (int)ch9-64;
    cout<<"I = "<<i<<endl;
    char ch10 = 'J';
    int j = (int)ch10-64;
    cout<<"J = "<<j<<endl;
    char ch11 = 'K';
    int k = (int)ch11-64;
    cout<<"K = "<<k<<endl;
    char ch12 = 'L';
    int l = (int)ch12-64;
    cout<<"L = "<<l<<endl;
    char ch13 = 'M';
    int m = (int)ch13-64;
    cout<<"M = "<<m<<endl;
    char ch14 = 'N';
    int n = (int)ch14-64;
    cout<<"N = "<<n<<endl;
    char ch15 = 'O';
    int o = (int)ch15-64;
    cout<<"O = "<<o<<endl;
    char ch16 = 'P';
    int p = (int)ch16-64;
    cout<<"P = "<<p<<endl;
    char ch17 = 'Q';
    int q = (int)ch17-64;
    cout<<"Q = "<<q<<endl;
    char ch18 = 'R';
    int r = (int)ch18-64;
    cout<<"R = "<<r<<endl;
    char ch19 = 'S';
    int s = (int)ch19-64;
    cout<<"S = "<<s<<endl;
    char ch20 = 'T';
    int t = (int)ch20-64;
    cout<<"T = "<<t<<endl;
    char ch21 = 'U';
    int u = (int)ch21-64;
    cout<<"U = "<<u<<endl;
    char ch22 = 'V';
    int v = (int)ch22-64;
    cout<<"V = "<<v<<endl;
    char ch23 = 'W';
    int w = (int)ch23-64;
    cout<<"W = "<<w<<endl;
    char ch24 = 'X';
    int x = (int)ch24-64;
    cout<<"X = "<<x<<endl;
    char ch25 = 'Y';
    int y = (int)ch25-64;
    cout<<"Y = "<<y<<endl;
    char ch26 = 'Z';
    int z = (int)ch26-64;
    cout<<"Z = "<<z<<endl;
    cout<<endl<<endl;

    

    return 0;
}